In [27]:
# Q.1 = Write statement to import numpy?
import numpy as np

In [28]:
#Q.2 = Create an array using numpy ?
import numpy as np
a=np.array([10,20,30,40])
a


array([10, 20, 30, 40])

In [29]:
#Q.3 = Create an array of 10 random integers ?
a=np.random.randint(1,100,10)
a

array([38, 17, 32, 94, 24, 18, 74,  7, 90, 99])

In [30]:
#Q.4 = Create an array of elements from 10-20?


a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
#Q.6 = Create a one dimensional array and convert that into 3*3 matrix ?

a=np.array([1,2,3,4,5,6,7,8,9])
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
#Q.5 = Create an array which contains value 5, 10 times ?
a=np.random.randint(5,6,10)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [33]:
#Q.7 = Create a 2D array of size 3*3 but all the elements should be between 0 to 1?
a=np.random.rand(3,3)
a

array([[0.42247324, 0.22135105, 0.13108999],
       [0.36179777, 0.67086895, 0.79338884],
       [0.48678737, 0.08837843, 0.83845047]])

In [34]:
#Q.8 = Concatenate 2D array horizontally and vertically?
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([10,20,30,40]).reshape(2,2)
np.hstack((a,b))


array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])

In [25]:

np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [10, 20],
       [30, 40]])